config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }, path: '', path_names: { sign_in: 'sign_in', sign_up: 'sign_up' }

  root "tasks#index"
  resources :account_deactivation, only: %i[index]
  namespace :account do
    resources :profile, only: %i[index update destroy]
    resources :statuses, only: %i[update]
  end

  namespace :admin do
    resources :users, only: %i[index show update]
    resources :statuses, only: %i[update]
  end

  resources :tasks
  resources :categories

  resources :privacy_policies

  resources :mark_as_done, only: %i[update]
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  validates :title, presence: true

  enum mark_as_done: {
    false: 0,
    true: 1
  }, _prefix: true


  enum status: {
    active: 0,
    archived: 1,
    completed: 2
  }, _prefix: true

  store :notify, accessors: [ :start_time, :reminder_at ], coder: JSON
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :account_deactivation!
  before_action :set_task
  def index
    @tasks = current_user.tasks.order(created_at: :desc)
    @google_classroom_tasks = Utils::User::GoogleClassroom.new(current_user).course_work

    render partial: 'tasks/google_classroom_frame' if turbo_frame_request?
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.turbo_stream { render turbo_stream: turbo_stream.prepend('tasks', partial: 'tasks/task', locals: { task: @task }) }
        format.html { redirect_to root_path, notice: "Task added successfully!" }
      else
        format.html { redirect_to root_path, alert: @task.errors.full_messages.first }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@task, partial: 'tasks/task', locals: { task: @task }) }
        format.html { redirect_to root_path, notice: "Task updated successfully!" }
      else
        format.html { redirect_to root_path, alert: @task.errors.full_messages.first }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @task.destroy
        format.html { redirect_to root_path, notice: "Task deleted successfully!" }
      else
        format.html { redirect_to root_path, alert: "Oops! Something went wrong while deleting the task." }
      end
    end
  end

  private

  def set_task
    @task = Task.find_by(id: params[:id])
  end

  def task_params
    params.require(:task).permit(
      :title,
      :notes,
      :due_date,
      :mark_as_done,
      :category_id
    ).merge(user_id: current_user.id)
  end
  def account_deactivation!
    if current_user.status_inactive?
      redirect_to account_deactivation_index_path, flash: { error: "You are taking a break from Tasktifier" }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_archived_task.html.erb
<div class="card border border-0 d-none d-md-block">
  <ul class="list-group d-flex flex-row p-2 align-items-center gap-2  bg-muted">
    <input class="form-check-input ms-2 col-1" type="checkbox" name="listGroupRadio" value="" checked>
    <div class="d-flex flex-column align-items-start align-items-md-center col-9" data-bs-toggle="modal" data-bs-target="#show_task_<%= dom_id(task)%>_modal">
      <label class="form-check-label" for="future_task_<%= dom_id(task) %>"><%= task.title %></label>
      <div class="d-flex align-items-center">
        <p class="mb-0 text-info"><%= format_due_date(task.due_date) %> <%= format_start_time(task.start_time) %></p>
        <%= bootstrap_icon 'bell-fill', class: 'ms-2'%><%= bootstrap_icon 'list-task', class: 'ms-2'%>
      </div>
    </div>
    <%= link_to "Classroom link", task.url, class: "btn btn-sm btn-primary text-success" unless task.url.nil? %>
  </ul>

  <div class="modal fade" id="show_task_<%= dom_id(task)%>_modal" tabindex="-1" aria-labelledby="show_task_<%= dom_id(task)%>_modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body d-flex flex-column align-items-end">
          <p class="text-info me-4"> Archived Task. </p>
          <%= button_to task_path(task), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger', title: 'Delete' do %>
            Remove
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<!-- Mobile Vew -->
<div class="d-block d-md-none pt-2" id="future">
  <div class="card border border-0 d-flex align-items-center justify-content-center flex-row  bg-muted">
    <div class='text-decoration-none list-group d-flex flex-row p-2 align-items-center  bg-muted w-100 'data-bs-toggle="modal" data-bs-target="#mobile_show_task_<%= dom_id(task)%>_modal">
      <input class="form-check-input ms-2 col-1" type="checkbox" name="listGroupRadio" value="" checked>
      <div class="d-flex flex-column align-items-center col-10">
        <label class="form-check-label" for="future_task_<%= dom_id(task) %>"><%= truncate_text(task.title) %></label>
        <div class="d-flex align-items-center">
          <p class="mb-0 text-info"><%= format_due_date(task.due_date) %> <%= format_start_time(task.start_time) %></p>
          <%= bootstrap_icon 'bell-fill', class: 'ms-2'%><%= bootstrap_icon 'list-task', class: 'ms-2'%>
        </div>
      </div>
    </div>
    <div class="modal fade" id="mobile_show_task_<%= dom_id(task)%>_modal" tabindex="-1" aria-labelledby="mobile_show_task_<%= dom_id(task)%>_modalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body d-flex flex-column align-items-end">
            <p class="text-info me-4"> Archived Task. </p>
            <%= button_to task_path(task), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger', title: 'Delete' do %>
              Remove
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_category_pane.html.erb
<div class='tab-pane fade' id='<%= remove_whitespace(category.name) %>' role='tabpanel'>
  <% if category.tasks.where(mark_as_done: 'false').exists? %>
    <%= render partial: 'tasks/task', collection: category.tasks.where(mark_as_done: 'false') %>
  <% else %>
    <%= render partial: 'tasks/no_task', locals: { user: user } %>
  <% end %>
</div>

app/views/tasks/_category_tab.html.erb
<a class='nav-link text-nowrap' data-bs-toggle='tab' href='#<%= remove_whitespace(category.name) %>' role='tab' aria-selected='true'>
  <%= category.name.capitalize %>
</a>

app/views/tasks/_completed_task.html.erb
<div class="card border border-0 d-none d-md-block">
  <ul class="list-group d-flex flex-row p-2 align-items-center gap-2  bg-secondary">
    <input class="form-check-input ms-2 col-1" type="checkbox" name="listGroupRadio" value="" checked>
    <div class="d-flex flex-column align-items-start align-items-md-center col-9" data-bs-toggle="modal" data-bs-target="#show_task_<%= dom_id(task)%>_modal">
      <label class="form-check-label" for="future_task_<%= dom_id(task) %>"><%= task.title %></label>
      <div class="d-flex align-items-center">
        <p class="mb-0 text-info"><%= format_due_date(task.due_date) %> <%= format_start_time(task.start_time) %></p>
        <%= bootstrap_icon 'bell-fill', class: 'ms-2'%><%= bootstrap_icon 'list-task', class: 'ms-2'%>
      </div>
    </div>
    <%= link_to "Classroom link", task.url, class: "btn btn-sm btn-primary text-success" unless task.url.nil? %>
  </ul>

  <div class="modal fade" id="show_task_<%= dom_id(task)%>_modal" tabindex="-1" aria-labelledby="show_task_<%= dom_id(task)%>_modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p class="text-info"> This task mask as done you can now remove this task. </p>
          <%= button_to task_path(task), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger', title: 'Delete' do %>
            Remove
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<!-- Mobile Vew -->
<div class="d-block d-md-none pt-2" id="future">
  <div class="card border border-0 d-flex align-items-center justify-content-center flex-row  bg-secondary">
    <div class='text-decoration-none list-group d-flex flex-row p-2 align-items-center  bg-secondary w-100 'data-bs-toggle="modal" data-bs-target="#mobile_show_task_<%= dom_id(task)%>_modal">
      <input class="form-check-input ms-2 col-1" type="checkbox" name="listGroupRadio" value="" checked>
      <div class="d-flex flex-column align-items-center col-10">
        <label class="form-check-label" for="future_task_<%= dom_id(task) %>"><%= truncate_text(task.title) %></label>
        <div class="d-flex align-items-center">
          <p class="mb-0 text-info"><%= format_due_date(task.due_date) %> <%= format_start_time(task.start_time) %></p>
          <%= bootstrap_icon 'bell-fill', class: 'ms-2'%><%= bootstrap_icon 'list-task', class: 'ms-2'%>
        </div>
      </div>
    </div>
    <div class="modal fade" id="mobile_show_task_<%= dom_id(task)%>_modal" tabindex="-1" aria-labelledby="mobile_show_task_<%= dom_id(task)%>_modalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p class="text-info"> This task mask as done you can now remove this task. </p>
            <%= button_to task_path(task), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger', title: 'Delete' do %>
              Remove
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_desktop_form.html.erb
<div class="container-fluid">
  <%= form_with(model: @task, url: task_path(@task), method: :put, data: { turbo: false }) do |form| %>
    <div class="form-group">
      <div class="mb-3 d-flex flex-row justify-content-between">
      <%= form.select :category_id, options_for_select(current_user.categories.where.not(id: @task.category_id).pluck(:name, :id)), { include_blank: @task.category.present? ? @task.category.name : 'No Category' }, class: 'form-select bg-dark text-light', id: 'task_category' %>
      </div>
      <div class="mb-4">
        <%= form.text_field :title, class: 'form-control bg-body text-light border border-0 px-2', placeholder: 'Input new task here...'%>
      </div>

      <div class="mb-4">
        <input class="form-check-input ms-2 col-2" type="checkbox" name="listGroupRadio" value="<%= @task.id %>" data-controller="mark-as-done"  data-action="change->mark-as-done#updateTask"> Mark as done
      </div>
      <ul class="list-group ">
        <li class="list-group-item bg-dark border border-0  d-flex align-items-center">
          <div class="col-6 d-flex align-items-center">
            <%= bootstrap_icon 'calendar-event', class: 'text-warning'%><span class="ms-2 text-light"> Due Date </span>
          </div>
          <div class="col-6">
            <%= form.date_field :due_date, class: 'bg-primary text-light border border-0 px-2', value: Date.tomorrow %>
          </div>
        </li>
        <li class="list-group-item bg-dark border border-0  d-flex align-items-center">
          <div class="col-6 d-flex align-items-center">
            <%= bootstrap_icon 'card-text', class: 'text-warning'%><span class="ms-2 text-light">Notes</span>
          </div>
          <div class="col-6">
            <%= form.text_area :notes, class: 'form-control' %>
          </div>
        </li>
      </ul>
    </div>
    <div class="modal-footer">
      <%= form.submit 'Update', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/tasks/_footer.html.erb
<ul class='list-group list-group-horizontal bg-primary d-md-none fixed-bottom'>
  <li class='btn btn-outline-primary border border-0 rounded-0 list-group-item d-md-none d-flex align-items-center bg-warning' data-bs-toggle='offcanvas' data-bs-target='#sideNav' aria-controls='sideNav'>
      <%= bootstrap_icon 'list' %>
  </li>
  <%= link_to tasks_path , class: 'btn btn-outline-primary border border-0 rounded-0 list-group-item d-md-none d-flex flex-column align-items-center justify-content-center w-100 text-decoration-none' do %>
    <%= bootstrap_icon 'list-task' %>
    <p class='mb-0' style='font-size: .5rem'>Tasks</p>
  <% end %>
  <%= link_to categories_path , class: 'btn btn-outline-primary border border-0 rounded-0 list-group-item d-md-none d-flex flex-column align-items-center justify-content-center w-100 text-decoration-none' do %>
    <%= bootstrap_icon 'grid-fill' %>
    <p class='mb-0' style='font-size: .5rem'>Categories</p>
  <% end %>

  <%= link_to account_profile_index_path, class: 'btn btn-outline-primary border border-0 rounded-0 list-group-item d-md-none d-flex flex-column align-items-center justify-content-center w-100' do %>
    <%= bootstrap_icon 'person' %>
    <p class='mb-0' style='font-size: .5rem'>Mine</p>
  <% end %>
</ul>

app/views/tasks/_google_classroom_frame.html.erb
<%= turbo_frame_tag :google_classroom_tasks_loader do %>
  <%= turbo_stream.append :google_classroom_tasks_result_frame do %>
    <%= render partial: 'tasks/task', collection: @tasks.where(mark_as_done: 'false').where.not(url: nil), locals: { google_classroom_tasks: @google_classroom_tasks } %>
  <% end %>
<% end %>

app/views/tasks/_mobile_form.html.erb
<div class="container-fluid">
  <%= form_with(model: @task, url: task_path(@task), method: :put, data: { turbo: false }) do |form| %>
    <div class="card-header py-2">
      <div class="d-flex align-items-center justify-content-between gap-4">
        <%= link_to root_path do %>
          <%= bootstrap_icon 'arrow-left' %>
        <% end %>
      </div>
    </div>


    <div class="mb-4">
      <input class="form-check-input ms-2 col-2" type="checkbox" name="listGroupRadio" value="<%= @task.id %>" data-controller="mark-as-done"  data-action="change->mark-as-done#updateTask"> Mark as done
    </div>

    <div class="form-group">
      <div class="mb-3">
        <%= form.select :category_id, options_for_select(current_user.categories.where.not(id: @task.category_id).pluck(:name, :id)), { include_blank: @task.category.present? ? @task.category.name : 'No Category' }, class: 'form-select bg-dark text-light', id: 'task_category' %>
      </div>
      <div class="mb-4">
        <%= form.text_field :title, class: 'form-control bg-body text-light border border-0 px-2', placeholder: 'Input new task here...'%>
      </div>
      <div class="mb-4">
        <%= link_to "Classroom link", @task.url, class: "btn btn-sm btn-primary text-success" unless @task.url.nil? %>
      </div>

      <ul class="list-group ">
        <li class="list-group-item bg-dark border border-0  d-flex align-items-center">
          <div class="col-6 d-flex align-items-center">
            <%= bootstrap_icon 'calendar-event', class: 'text-warning' %><span class="ms-2 text-light"> Due Date </span>
          </div>
          <div class="col-6">
            <%= form.date_field :due_date, class: 'bg-primary text-light border border-0 px-2', value: Date.tomorrow %>
          </div>
        </li>
        <li class="list-group-item bg-dark border border-0  d-flex align-items-center">
          <div class="col-6 d-flex align-items-center">
            <%= bootstrap_icon 'card-text', class: 'text-warning'%><span class="ms-2 text-light">Notes</span>
          </div>
          <div class="col-6">
            <%= form.text_area :notes, class: 'form-control' %>
          </div>
        </li>
      </ul>
    </div>
    <div class="modal-footer mt-4">
      <%= form.submit 'Update', class: 'btn btn-primary w-100' %>
    </div>
  <% end %>
</div>

app/views/tasks/_no_task.html.erb
<div class='d-flex flex-column align-items-center justify-content-center p-5'>
  <%= image_tag 'task', class:'img-fluid'%>
  <p>Welcome, <span class='text-warning'><%= username %>!</span> Let's get started on your tasks!</p>
</div>

app/views/tasks/_placeholder.html.erb
<div class="shimmer-wrapper d-flex align-items-center justify-content-center p-5">
  <div class="spinner-border text-warning" role="status">
  </div>
  <span class="ms-2">Please wait...</span>
</div>

app/views/tasks/_placeholder_spinner.html.erb
<div class="shimmer-wrapper d-flex align-items-center justify-content-center p-5">
  <div class="spinner-border text-warning" role="status">
  </div>
  <span class="ms-2">Please wait...</span>
</div>

app/views/tasks/_task.html.erb
<div class="card border border-0 d-none d-md-block">
  <ul class="list-group d-flex flex-row p-2 align-items-center gap-2 bg-primary ">
    <input class="form-check-input ms-2 col-2" type="checkbox" name="listGroupRadio" value="<%= task.id %>" data-controller="mark-as-done"  data-action="change->mark-as-done#updateTask">
    <div class="d-flex flex-column align-items-start align-items-md-center col-9" data-bs-toggle="modal" data-bs-target="#show_task_<%= dom_id(task)%>_modal">
      <label class="form-check-label" for="future_task_<%= dom_id(task) %>"><%= task.title %></label>
      <div class="d-flex align-items-center">
        <p class="mb-0 text-info"><%= format_due_date(task.due_date) %> <%= format_start_time(task.start_time) %></p>
        <%= bootstrap_icon 'bell-fill', class: 'ms-2'%><%= bootstrap_icon 'list-task', class: 'ms-2'%>
      </div>
    </div>
    <%= link_to "Classroom link", task.url, class: "btn btn-sm btn-primary text-success" unless task.url.nil? %>
    <%= button_to task_path(task), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger', title: 'Delete' do %>
      Remove
    <% end %>
  </ul>

  <div class="modal fade" id="show_task_<%= dom_id(task)%>_modal" tabindex="-1" aria-labelledby="show_task_<%= dom_id(task)%>_modalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= turbo_frame_tag :edit_task_frame, src: edit_task_path(task) do %>
          Loading...
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>
<!-- Mobile Vew -->
<div class="d-block d-md-none pt-2" id="future">
  <div class="card border border-0 d-flex align-items-center justify-content-center flex-row bg-primary">
      <input class="form-check-input ms-2 col-2" type="checkbox" name="listGroupRadio" value="<%= task.id %>" data-controller="mark-as-done"  data-action="change->mark-as-done#updateTask">
    <%= link_to edit_task_path(task), class:' text-decoration-none list-group d-flex flex-row p-2 align-items-center bg-primary w-100' do %>
      <div class="d-flex flex-column align-items-center col-10">
        <label class="form-check-label" for="future_task_<%= dom_id(task) %>"><%= truncate_text(task.title) %></label>
        <div class="d-flex align-items-center">
          <p class="mb-0 text-info"><%= format_due_date(task.due_date) %> <%= format_start_time(task.start_time) %></p>
          <%= bootstrap_icon 'bell-fill', class: 'ms-2'%><%= bootstrap_icon 'list-task', class: 'ms-2'%>
        </div>
      </div>
    <% end %>
      <%= link_to task_path(task), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'col-2 border border-0 text-center' do %>
      <%= bootstrap_icon 'trash', width: '1.2rem', class: 'text-danger'%>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag :edit_task_frame do %>
  <% if desktop_device? %>
    <%= render partial: 'tasks/desktop_form', local: { task: @task } %>
  <% else %>
    <%= render partial: 'tasks/mobile_form', local: { task: @task } %>
  <% end %>
<% end %>

app/views/tasks/index.html.erb
<div class='container-fluid'>
<% user = UserPresenter.new(current_user) %>
  <div class='row'>
    <div class='col min-vh-100 py-3'>
      <div class='row'>
        <div class='col-8 col-lg-8'>
          <button class='btn btn-outline-primary d-none d-md-inline' type='button' data-bs-toggle='offcanvas' data-bs-target='#sideNav' aria-controls='sideNav'>
            <%= bootstrap_icon 'list' %>
          </button>
        </div>

        <div class='col-4 col-lg-2 d-flex flex-row gap-2'>
            <button type='button' class='btn btn-primary text-nowrap' data-bs-toggle='modal' data-bs-target='#new_task_modal'>
              <p class="d-none d-lg-inline">Add task</p>
              <%= bootstrap_icon 'plus', width: '1rem', class: 'd-inline d-lg-none'%>
            </button>
            <button type='button' class='btn btn-primary text-nowrap' data-bs-toggle='modal' data-bs-target='#new_category_modal'>
              <p class="d-none d-lg-inline">Add category</p>
              <%= bootstrap_icon 'grid-fill', width: '1rem', class: 'd-inline d-lg-none'%>
            </button>
          <!-- Modal -->
          <div class='modal fade' id='new_task_modal' tabindex='-1' aria-labelledby='new_task_modalLabel' aria-hidden='true'>
            <div class='modal-dialog modal-dialog-centered'>
              <div class='modal-content'>
                <div class='modal-header'>
                  <p class='fw-bold text-light mb-0'>New task</p>
                  <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
                </div>
                <%= turbo_frame_tag :new_task_frame, src: new_task_path do %>
                  Loading...
                <% end %>
              </div>
            </div>
          </div>
          <div class='modal fade' id='new_category_modal' tabindex='-1' aria-labelledby='new_category_modalLabel' aria-hidden='true'>
            <div class='modal-dialog modal-dialog-centered'>
              <div class='modal-content'>
                <div class='modal-header'>
                  <p class='fw-bold text-light mb-0'>New category</p>
                  <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
                </div>
                <%= turbo_frame_tag :new_category_frame, src: new_category_path do %>
                  Loading...
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
     <!-- Button trigger modal -->
      <div class='container'>
        <nav class='nav nav-tabs gap-2 flex-row flex-nowrap py-2 overflow-auto <%= current_user.categories.present? ? '' : 'd-none' %>' style='overflow-y: hidden !important;'>
          <a class='nav-link text-nowrap active' data-bs-toggle='tab' href='#all' role='tab' aria-selected='true'>All</a>
          <%= render partial: 'tasks/category_tab', collection: user.categories, as: :category %>
        </nav>

        <div class='tab-content pt-2'>
          <div class='tab-pane fade show active' id='all' role='tabpanel'>
            <% unless @tasks.present? %>
              <%= render partial: 'tasks/no_task', locals: { user: user }%>
            <% else %>
                <% if @google_classroom_tasks.any? %>
                  <h5 class="text-warning">Classworks</h5>
                  <%= turbo_frame_tag :google_classroom_tasks_result_frame %>
                  <%= turbo_frame_tag :google_classroom_tasks_loader, src: tasks_path, loading: :lazy do %>
                    <%= render partial: "tasks/placeholder_spinner" %>
                  <% end %>
                <% end %>

                <% if @tasks.where(mark_as_done: 'false', url: nil, status: 'active').any? %>
                  <h5 class="text-warning">Current</h5>
                  <%= render partial: 'tasks/task', collection: @tasks.where(mark_as_done: 'false', url: nil) %>
                <% end %>

                <% if @tasks.where(mark_as_done: 'true', status: 'completed').any? %>
                  <h5 class="text-warning mt-2">Completed</h5>
                  <%= render partial: 'tasks/completed_task', collection: @tasks.where(mark_as_done: 'true', status: 'completed'), as: :task %>
                <% end %>

                <% if @tasks.where(status: 'archived').any? %>
                  <h5 class="text-warning mt-2">Archived</h5>
                  <%= render partial: 'tasks/archived_task', collection: @tasks.where(status: 'archived'), as: :task %>
                <% end %>
            <% end %>
          </div>
          <%= render partial: 'tasks/category_pane', collection: user.categories, as: :category, locals: { user: user } %>
        </div>
      </div>
      <!-- Mobile View  -->
      <%= render partial: 'tasks/footer'%>
    </div>
  </div>
</div>