config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }, path: '', path_names: { sign_in: 'sign_in', sign_up: 'sign_up' }

  root "tasks#index"
  resources :account_deactivation, only: %i[index]
  namespace :account do
    resources :profile, only: %i[index update destroy]
    resources :statuses, only: %i[update]
  end

  namespace :admin do
    resources :users, only: %i[index show update]
    resources :statuses, only: %i[update]
  end

  resources :tasks
  resources :categories

  resources :privacy_policies

  resources :mark_as_done, only: %i[update]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :account_deactivation!
  before_action :set_category


  def index
    @categories = current_user.categories.order(created_at: :desc)
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path, notice: "Category added successfully!" }
      else
        format.html { redirect_to root_path, alert: @category.errors.full_messages.first }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to root_path, notice: "Category updated successfully!" }
      else
        format.html { redirect_to root_path, alert: @category.errors.full_messages.first }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @category.destroy
        format.html { redirect_to root_path, notice: "Category deleted successfully!" }
      else
        format.html { redirect_to root_path, alert: "Oops! Something went wrong while deleting the category." }
      end
    end
  end

  private
  def set_category
    @category = Category.find_by(id: params[:id])
  end

  def category_params
    params.require(:category).permit(
      :name
    ).merge(user_id: current_user.id)
  end

  def account_deactivation!
    if current_user.status_inactive?
      redirect_to account_deactivation_index_path, flash: { error: "You are taking a break from Tasktifier" }
    end
  end
end

app/views/categories/_category.html.erb
<div class='list-group-item d-flex justify-content-between align-items-center bg-dark border border-0'>
  <div class="d-flex align-items-center justify-content-center gap-2">
    <%= bootstrap_icon 'circle-fill', class: 'text-warning' %><span class='ms-2'><%= category.name.capitalize %></span>
  </div>

  <div class="nav-item dropdown">
    <a class="nav-link" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      <%= bootstrap_icon 'three-dots-vertical' %>
    </a>
    <div class="dropdown-menu">
      <div class="dropdown-item" type='button' data-bs-toggle='modal' data-bs-target='#show_category_<%= dom_id(category)%>_modal'>Edit</div>
      <%= link_to category_path(category), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure' },class: 'text-decoration-none dropdown-item text-danger', title: 'Delete' do %>
        Delete
      <% end %>
    </div>
    <div class="modal fade" id="show_category_<%= dom_id(category)%>_modal" tabindex="-1" aria-labelledby="show_category_<%= dom_id(category)%>_modalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <p class='fw-bold text-light mb-0'>Edit category</p>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <%= turbo_frame_tag :edit_category_frame, src: edit_category_path(category) do %>
            Loading...
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category_tab.html.erb
<div class='list-group-item d-flex justify-content-between align-items-center bg-dark border border-0'><font style='vertical-align: inherit;'><font style='vertical-align: inherit;'>
  <%= bootstrap_icon 'list-task'%>
  <span class='ms-1'><%= category.name.capitalize %></span>
  </font></font><span class='badge bg-primary rounded-pill'><font style='vertical-align: inherit;'><font style='vertical-align: inherit;'><%= category.tasks.count %></font></font></span>
</div>

app/views/categories/edit.html.erb
<%= turbo_frame_tag :edit_category_frame do %>
  <div class="modal-body">
    <%= form_with(model: @category, data: { turbo: false }) do |form| %>
      <div class="form-group">
        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control bg-dark text-light', placeholder: 'Input new category here...', id: 'category_name', value: @category.name.capitalize %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <%= form.submit 'Update', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="container">
  <div class="row p-2 px-0">
    <div class="col-12 d-flex flex-row gap-3">
      <%= link_to root_path do %>
        <%= bootstrap_icon 'arrow-left', width: '1.5rem' %>
      <% end %>
      <p class='text-light fw-bold'>Manage Categories</p>
    </div>
    <div class="col-12 px-0">
      <div class="card-header bg-primary border border-0 text-light fw-light text-center p-2">
        Categories display on homepage
      </div>
      <div class="card-body">
        <ul class='d-flex flex-column p-4 gap-2'>
          <%= render partial: 'categories/category', collection: @categories %>
        </ul>
      </div>
      <div class="card-footer">
        <div class='d-flex flex-column py-4 px-3'>
          <div class='ms-1 list-group-item d-flex align-items-center bg-dark border border-0' type='button' data-bs-toggle='modal' data-bs-target='#new_category_modal'>
            <%= bootstrap_icon 'plus', width: '1.5rem', class: 'text-warning'%>
            <span class='ms-2 fw-bold text-warning'> Create New </span>
          </div>
          <div class='modal fade' id='new_category_modal' tabindex='-1' aria-labelledby='new_category_modalLabel' aria-hidden='true'>
            <div class='modal-dialog modal-dialog-centered'>
              <div class='modal-content'>
                <div class='modal-header'>
                  <p class='fw-bold text-light mb-0'>New category</p>
                  <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
                </div>
                <%= turbo_frame_tag :new_category_frame, src: new_category_path do %>
                  Loading...
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= turbo_frame_tag :new_category_frame do %>
  <div class="modal-body">
    <%= form_with(model: @category, data: { turbo: false }) do |form| %>
      <div class="form-group">
        <div class="mb-3">
          <%= form.label :name, class: 'form-label' %>
          <%= form.text_field :name, class: 'form-control bg-dark text-light', placeholder: 'Input new category here...', id: 'category_name' %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <%= form.submit 'Add task', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
<% end %>