config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }, path: '', path_names: { sign_in: 'sign_in', sign_up: 'sign_up' }

  root "tasks#index"
  resources :account_deactivation, only: %i[index]
  namespace :account do
    resources :profile, only: %i[index update destroy]
    resources :statuses, only: %i[update]
  end

  namespace :admin do
    resources :users, only: %i[index show update]
    resources :statuses, only: %i[update]
  end

  resources :tasks
  resources :categories

  resources :privacy_policies

  resources :mark_as_done, only: %i[update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]


  has_one_attached :avatar, dependent: :destroy

  has_many :tasks, dependent: :destroy
  has_many :categories, dependent: :destroy
  enum role: {
    regular: 0,
    admin: 1
  }, _prefix: true

  enum gender: {
    male: 0,
    female: 1,
    prefer_not_to_say: 2
  }, _prefix: true

  enum status: {
    active: 0,
    inactive: 1
  }, _prefix: true


  def admin?
    role_admin?
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data.email).first
    unless user
      # Create a new user with the provided access token
      user = User.create(
        email: data.email,
        google_uid: access_token.uid,
        google_provider: access_token.provider,
        role: :regular,
        google_token: access_token.credentials.token,
        google_token_expire_at: access_token.credentials.expires_at,
        google_refresh_token: access_token.credentials.refresh_token,

        password: Devise.friendly_token[0, 20]
      )
      user.avatar.attach(io: URI.open(data.image), filename: 'google_avatar.jpg')
    end
    if user.google_uid.nil?
      user.avatar.attach(io: URI.open(data.image), filename: 'google_avatar.jpg')
      user.update(google_uid: access_token.uid, google_provider: access_token.provider, google_token: access_token.credentials.token)
    elsif access_token.credentials.expires_at.present? && Time.now >= access_token.credentials.expires_at
      new_token = refresh_token(access_token.credentials.refresh_token)
      user.update(google_token: new_token)
    end

    user
  end

  def self.refresh_token(refresh_token)
    client = OAuth2::Client.new(ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], site: 'https://accounts.google.com')
    token = OAuth2::AccessToken.new(client, refresh_token)
    new_token = token.refresh!
    new_token.token
  end

  def self.ransackable_attributes(auth_object = nil)
    ["username", "email"]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  include AdminAccessible

  before_action :set_user, only: %i[show update destroy]

 def index
  @filtered_users = User.ransack(params[:q])
  @pagy, @users = pagy(@filtered_users.result.order(:created_at => :desc), items: 10)
 end


 def show; end

 def update
  respond_to do |format|
    if @user.update(user_params)
      flash_message = { success: "User updated successfully" }
    else
      flash_message = { error: @user.errors.full_messages.first }
    end
    format.turbo_stream { redirect_back fallback_location: admin_users_path, flash: flash_message }
  end
 end

 def destroy
  respond_to do |format|
  if @user.destroy
    flash_message = { success: "User deleted successfully" }
  else
    flash_message = { error: @user.errors.full_messages.first }
  end
    format.turbo_stream { redirect_back fallback_location: admin_users_path, flash: flash_message }
  end
end

private
  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :username,
      :gender,
      :email,
      :avatar,
      :role
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  #before_action :set_account

  def google_oauth2
    @user = User.from_omniauth(auth_params)

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = auth_params.except('extra') # Removing extra as it can overflow some session stores
      redirect_to new_user_session_path, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to user_session_path
  end

  private

  def auth_params
    request.env['omniauth.auth']
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!

  def update
    respond_to do |format|
      if resource.update(user_params)
        format.html { redirect_back fallback_location: account_profile_index_path, notice: "Profile updated successfully" }
      else
        format.html { redirect_back fallback_location: account_profile_index_path, alert: resource.errors.full_messages.first }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :password,
      :password_confirmation
    ).merge(email: current_user.email)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new
    @user = User.new
  end


  def create
    self.resource = warden.authenticate(auth_options)

    if resource && resource.active_for_authentication?
        redirect_to root_path, flash: { success: "Successfully Signed in" }
    else
        redirect_to new_user_session_path, flash: { invalid_sign_in: "Invalid login credentials" }
    end
  end

  def destroy
    super
  end

  private

  def after_sign_out_path_for(resource)
    user_session_path
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/admin/users/_dashboard.html.erb
<table class="table">
  <tr>
    <td>
      <div class="card p-2 shadow border border-0">
        <div class="card-header w-100 text-end border border-0", style="background-color: #32383e">
        </div>
        <div class="card-body d-flex flex-column align-items-center justify-content-center mt-4 text-nowrap">
          <h3 clas="fw-bold"><%= user.tasks.where(mark_as_done: 'true').count %></h3>
          <p class="text-info">Completed Tasks</p>
        </div>
      </div>
    </td>
    <td>
      <div class="card p-2 shadow border border-0">
        <div class="card-header w-100 text-end border border-0", style="background-color: #32383e">
          <%= bootstrap_icon 'question-circle', class: 'text-warning',
            width: '1.3rem',
            data: { bs_toggle: 'tooltip', bs_placement: 'left', bs_original_title: 'All tasks undone to be processed.' }
          %>
        </div>
        <div class="card-body d-flex flex-column align-items-center justify-content-center text-nowrap ">
          <h3 clas="fw-bold"><%= user.tasks.where(mark_as_done: 'false').count %></h3>
          <p class="text-info">Pending Tasks</p>
        </div>
      </div>
    </td>
  </tr>
</table>

app/views/admin/users/_layout.html.erb
<div class="container py-3 py-sm-5 px-sm-0">
  <div class="row profile">
    <aside class="col-12 col-lg-3 text-center p-3">
      <div class="d-flex align-items-start">
        <%= link_to admin_users_path, class: 'text-decoration-none text-warning' do %>
          <%= bootstrap_icon 'arrow-left', width: '1.2rem' %>
        <% end %>
      </div>
      <div class="border border-0">
        <%= render partial: "admin/users/form/change_avatar", locals: { user: user } %>
        <h5 class="py-2"><%= user_username(user) %></h5>
        <hr class="mx-4 my-4">
        <p class="text-warning">Total Tasks: <span class="text-info"><%= user.tasks.count %></span></p>
      </div>
    </aside>
    <div class="col-12 col-lg-9 pt-5">
      <%= yield %>
    </div>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tr class="text-center">
  <td><%= user.id %></td>
  <td><%= image_tag user_profile_picture(user), style:"width: 2rem; height: 2rem;"%></td>
  <td><%= user_username(user) %></td>
  <td><%= user.email %></td>
  <td><%= user.gender %></td>
  <td><%= user.tasks.count %></td>
  <td class="<%= user.status_active? ? 'text-success' : 'text-danger' %>"><%= user.status %></td>
  <td>
   <div class="btn-group">
      <button class="btn btn-secondary dropdown-toggle text-warning" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Action
      </button>
      <ul class="dropdown-menu">
        <%= link_to "View", admin_user_path(user), class: "dropdown-item" %>
        <%= button_to "#{user.status_active? ? 'Deactivate' : 'Activate'}", admin_status_path(user),class: 'dropdown-item text-danger', data: { controller: 'account--deactivation', action: 'click->account--deactivation#updateStatus', confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :patch  %>
      </ul>
    </div>
  </td>
</tr>

app/views/admin/users/index.html.erb
<div class="card my-3 shadow-sm">
  <div class="card-header border-0 p-4 d-flex justify-content-between">
    <%= search_form_for @filtered_users, url: admin_users_path, class: "d-flex alignitems-center position-relative" do |form| %>
      <%= bootstrap_icon 'search', class:'text-secondary position-absolute ms-2 mt-2', width: '2rem'%>
      <%= form.search_field :username_cont,
        class: "form-control form-control-solid ps-5",
        placeholder: "Search User",
        autocomplete: "off"
      %>
    <% end %>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table align-middle">
        <thead>
          <tr class="text-center">
            <th scope="col">Id</th>
            <th scope="col">Avatar</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Gender</th>
            <th scope="col">Total Tasks</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
          </tr>
        </thead>

        <tbody>
          <% if @users.present? %>
            <%= render partial: "admin/users/user", collection: @users, as: :user %>
          <% else %>
            <tr class="text-center">
              <td class="h3 opacity-25 py-4" colspan="4">
                <%= bootstrap_icon 'search', class: 'text-warning me-3' %> No results found.
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) if @users.present? %>
  </div>
</div>

app/views/admin/users/show.html.erb
<%= render layout: "admin/users/layout", locals: { user: @user } do %>
  <div class="px-sm-3">
    <ul class="nav nav-pills mb-3 gap-2 flex-row flex-nowrap overflow-auto py-2 style='overflow-y: hidden !important;'" id="pills-tab" role="tablist" >
      <li class="nav-item" role="presentation">
        <button class="nav-link <%= params[:tab] == "settings" ? '' : 'active' %> " id="pills-dashboard-tab" data-bs-toggle="pill" data-bs-target="#pills-dashboard" type="button" role="tab" aria-controls="pills-dashboard" aria-selected="true">Dashboard</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-details-tab" data-bs-toggle="pill" data-bs-target="#pills-details" type="button" role="tab" aria-controls="pills-details" aria-selected="false">Details</button>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade <%= params[:tab] == "settings" ? ' ' : 'show active'%>" id="pills-dashboard" role="tabpanel" aria-labelledby="pills-dashboard-tab" tabindex="0">
        <%= render partial: "admin/users/dashboard", locals: { user: @user } %>
      </div>
      <div class="tab-pane fade" id="pills-details" role="tabpanel" aria-labelledby="pills-details-tab" tabindex="0">
        <%= render partial: "admin/users/form/profile_details", locals: { user: @user } %>
      </div>
    </div>
    <hr class="mt-5 mb-4">
  </div>
<% end %>