config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }, path: '', path_names: { sign_in: 'sign_in', sign_up: 'sign_up' }

  root "tasks#index"
  resources :account_deactivation, only: %i[index]
  namespace :account do
    resources :profile, only: %i[index update destroy]
    resources :statuses, only: %i[update]
  end

  namespace :admin do
    resources :users, only: %i[index show update]
    resources :statuses, only: %i[update]
  end

  resources :tasks
  resources :categories

  resources :privacy_policies

  resources :mark_as_done, only: %i[update]
end

app/views/layouts/_sidenav.html.erb
<%  user = UserPresenter.new(current_user) %>
<div class='offcanvas  offcanvas-start' tabindex='-1' id='sideNav' aria-labelledby='sideNavLabel'>
  <div class='offcanvas-header bg-primary'>
    <div class='dropdown'>
      <a href='#' class='nav-link dropdown-toggle ' id='dropdown' data-bs-toggle='dropdown' aria-expanded='false'>
        <span class='ms-1'>
          <%= image_tag profile_picture, class: 'rounded-circle', style:"width: 2rem; height: 2rem;"%>
        </span>
        <span class='ms-1 text-light'><%= username %></span>
      </a>
      <ul class='dropdown-menu text-small shadow' aria-labelledby='dropdown'>
        <% if current_user.admin? %>
          <li>
            <%= link_to admin_users_path, class: 'dropdown-item' do %>
              <%= bootstrap_icon 'speedometer2', class: 'text-warning' %>
              <span class='ms-1'> Admin Dashboard </span>
            <% end %>
          </li>
        <% end %>
        <li>
          <%= link_to account_profile_index_path(tab: ""), class: 'dropdown-item' do %>
            <%= bootstrap_icon 'person-circle', class: 'text-warning'%>
            <span class='ms-1'>View Profile</span>
          <% end  %>
        </li>
        <li>
            <hr class='dropdown-divider'>
        </li>
        <li>
        <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item', data: { turbo_method: :delete } do %>
          <%= bootstrap_icon 'box-arrow-in-right', class: 'text-warning' %>
          <span class='ms-1'>Logout</span>
        <% end %>
        </li>
      </ul>
    </div>
    <button type='button' class='btn-close' data-bs-dismiss='offcanvas' aria-label='Close'></button>
  </div>
  <div class='offcanvas-body'>
      <div class='cover-logo'>
        <%= image_tag 'header-logo', class:'img-fluid'%>
      </div>
      <ul class='nav flex-column mb-sm-auto mb-0 align-items-start' id='menu'>
        <%= link_to categories_path, class: 'nav-item text-decoration-none' do %>
          <div class="nav-link">
            <%= bootstrap_icon 'grid-fill', class: 'text-warning'%>
            <span class='ms-1'>Categories</span>
          </div>
        <% end %>
        <li class='category-list w-100 nav-item'>
          <div class='card bg-dark border border-0'>
            <ul class='list-group'>
              <%= link_to tasks_path , class: 'list-group-item d-flex justify-content-between align-items-center bg-dark border border-0' do %>
                <font style='vertical-align: inherit;'><font style='vertical-align: inherit;'>
                <%= bootstrap_icon 'list-task'%>
                <span class='ms-1'>All</span>
                </font></font><span class='badge bg-primary rounded-pill'><%= user.total_tasks %></span>
              <% end %>
              <%= render partial: 'categories/category_tab', collection: user.categories, as: :category %>
            </ul>
          </div>
        </li>
        <li>
          <%= link_to account_profile_index_path(tab: "settings"), class: 'nav-link text-decoration-none' do %>
            <%= bootstrap_icon 'gear-fill', class: 'text-warning'%>
            <span class='ms-1'>Settings</span>
          <% end %>
        </li>
      </ul>
    </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin-Tasktifier</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'logo.png' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
  <body class="container-fluid admin">
    <div class="row">
      <%= render "layouts/admin/header" %>
      <%= render "layouts/admin/sidebar" %>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <%= render "layouts/common/flash_message" %>
        <%= yield %>
      </main>
    </div>
      <%= render "layouts/common/confirm_dialog" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Tasktifier</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'logo.png' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
  <body>
    <%= render partial: 'layouts/common/flash_message'%>
    <%= render partial: 'layouts/sidenav' if user_signed_in? %>
    <%= yield %>
    <%= render partial: "layouts/common/confirm_dialog" %>
  </body>
</html>